#!/usr/bin/perl
# Скрипт для генерации превьюшек из видео с несколькими кадрами

use strict;

die "USAGE: $0 INPUT-VIDEO WIDTH HEIGHT OUTPUT-FILE [N]" if @ARGV < 4;

my ($input, $width, $height, $output, $n) = @ARGV;
my $identify = `ffmpeg -i '$input' -an -vcodec copy -f avi -y /dev/null 2>&1`;
my ($len) = $identify =~ /time=\s*([\d\.]+).*?$/so;
$n = 2 unless $n && $n > 1;
my $s;
my $i = 0;
my ($cj, $ci);
$ci = "";
for my $i (0..$n-1)
{
    $cj = "";
    for my $j (0..$n-1)
    {
        $s = sprintf("%.2d", $len*($i*$n+$j)/$n/$n);
        system("ffmpeg -ss '$s' -i '$input' -vframes 1 -f image2 -y '$output.$i.$j.png'");
        $cj .= " '$output.$i.$j.png'";
    }
    system("convert $cj +append '$output.$i.png'; rm $cj");
    $ci .= " '$output.$i.png'";
}
system("convert $ci -append -resize ${width}x${height} '$output'; rm $ci");
