#!/usr/bin/perl
# Скрипт для генерации превьюшек из видео с несколькими кадрами

use strict;

die "USAGE: $0 INPUT-VIDEO WIDTH HEIGHT OUTPUT-FILE [Nx] [Ny]" if @ARGV < 4;

my ($input, $width, $height, $output, $nx, $ny) = @ARGV;
my $identify = `ffmpeg -i '$input' -an -vcodec copy -f avi -y /dev/null 2>&1`;
my ($len) = $identify =~ /time=\s*([\d\.]+).*?$/so;
$nx = 2 unless $nx && $nx > 0;
$ny = 2 unless $ny && $ny > 0;
my $s;
my $i = 0;
my ($cj, $ci);
$ci = "";
for my $i (0..$ny-1)
{
    $cj = "";
    for my $j (0..$nx-1)
    {
        $s = sprintf("%.2d", $len*($i+($j+0.5)/$nx)/$ny);
        system("ffmpeg -ss '$s' -i '$input' -vframes 1 -f image2 -y '$output.$i.$j.png'");
        $cj .= " '$output.$i.$j.png'";
    }
    if ($nx > 1)
    {
        system("convert $cj +append '$output.$i.png'; rm $cj");
        $ci .= " '$output.$i.png'";
    }
    else
    {
        $ci .= $cj;
    }
}

system("convert $ci ".($ny > 1 ? '-append' : '')." -resize ${width}x${height} '$output'; rm $ci");
